#!/bin/bash
set -euxo pipefail

mkdir /work
cd /work

export DEBIAN_FRONTEND=noninteractive
apt-get update
apt-get -y install --no-install-recommends \
    build-essential \
    cmake \
    git \
    libbz2-dev \
    libfluidsynth-dev \
    libgme-dev \
    libgtk-3-dev \
    libmpg123-dev \
    libopenal-dev \
    libsdl2-dev \
    libsndfile1-dev \
    nasm \
    zlib1g-dev \
    ;

git clone $GIT_OPTIONS ${GIT_REPO:-https://github.com/coelckers/gzdoom.git} gzdoom

mkdir -p gzdoom/build
cd gzdoom/build
cmake .. $CMAKE_OPTIONS -DNO_FMOD=ON
make $MAKE_OPTIONS

install -o "$DIST_UID" -g "$DIST_GID" -m 755 gzdoom /mnt/dist
install -o "$DIST_UID" -g "$DIST_GID" -m 644 *.pk3 /mnt/dist
